table 'Term Sort'
	lineageTag: 99825fd6-05a8-4792-bb23-4af0b3c642c0

	column Sort
		dataType: int64
		formatString: 0
		lineageTag: 6e2e2eb4-1c74-435d-a571-4a0b1ef254c7
		summarizeBy: none
		sourceColumn: Sort

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: e50d7ac7-de1b-4860-9dd5-60a4c043479b
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition 'Term Sort' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlHSUQouKMrMS1eK1YlWMgZywzPzSlKLwFxDkGxpbi6UawTkOpaWlObmKcXGAgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [academicQuarter = _t, Quarter = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"academicQuarter", Int64.Type}, {"Quarter", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"academicQuarter", "Sort"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

